# Site settings
name: 我的博客
email: a879998991@qq.com
author: lihao
url: http://www.baidu.com
resume_site: http://www.baidu.com/
github: https://github.com/lihao87999/
baseurl:  
description: 生命不止 折腾不休
meta_description: lihao;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 见闻 灵感 突发奇想
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: hao87999

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

